# Generated by Django 2.1 on 2020-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_auto_20200427_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
