# Generated by Django 2.1 on 2020-04-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200429_2237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagprojects',
            new_name='Tag_projects',
        ),
        migrations.AlterField(
            model_name='rate',
            name='body',
            field=models.IntegerField(verbose_name=(0, 1, 2, 3, 4)),
        ),
    ]
