# Generated by Django 2.1 on 2020-05-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200430_1541'),
        ('projects', '0003_auto_20200430_2313'),
        ('projects', '0002_auto_20200430_1654'),
    ]

    operations = [
    ]
