# Generated by Django 2.1 on 2020-04-21 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200421_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tage',
            new_name='Tag',
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='user_Donate', to=settings.AUTH_USER_MODEL),
        ),
    ]
