# Generated by Django 2.1 on 2020-04-22 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0008_auto_20200421_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Pictures',
            new_name='ProjectPictures',
        ),
        migrations.RenameModel(
            old_name='Report_comment',
            new_name='ReportComment',
        ),
        migrations.RenameModel(
            old_name='Report_project',
            new_name='ReportProject',
        ),
        migrations.RenameModel(
            old_name='Selected_To_Show',
            new_name='SelectedToShow',
        ),
        migrations.AlterField(
            model_name='rate',
            name='body',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4)),
        ),
    ]
