# Generated by Django 2.1 on 2020-04-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200423_0205'),
        ('projects', '0013_auto_20200423_0444'),
    ]

    operations = [
    ]
