# Generated by Django 2.1 on 2020-04-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20200424_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='body',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4)),
        ),
    ]
