# Generated by Django 2.1 on 2020-04-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200424_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='body',
            field=models.IntegerField(verbose_name=(1, 2, 3, 4)),
        ),
        migrations.AlterUniqueTogether(
            name='donate',
            unique_together=set(),
        ),
    ]
