# Generated by Django 2.1 on 2020-04-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200424_2230'),
        ('projects', '0016_auto_20200424_2116'),
    ]

    operations = [
    ]
