# Generated by Django 2.1 on 2020-04-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200425_0234'),
        ('projects', '0017_auto_20200427_0230'),
    ]

    operations = [
    ]
