# Generated by Django 2.1 on 2020-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20200427_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='body',
            field=models.IntegerField(verbose_name=(0, 1, 2, 3, 4)),
        ),
    ]
