# Generated by Django 2.1 on 2020-04-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20200427_1732'),
        ('projects', '0024_auto_20200428_0131'),
    ]

    operations = [
    ]
