# Generated by Django 2.1 on 2020-04-28 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_merge_20200428_2041'),
        ('projects', '0027_auto_20200428_0343'),
    ]

    operations = [
    ]
